// Simplified Pokedex with Gen 4 (Diamond/Pearl/Platinum) focus
// Includes primary types for soul-locke rules

export interface PokedexEntry {
  name: string;
  species: string;
  primaryType: string;
}

// Comprehensive Gen 4 / Platinum-available Pokédex entries
// Keyed by lowercase name — no duplicates
const POKEDEX_DATA: Record<string, PokedexEntry> = {
  // Gen 1
  bulbasaur:   { name: 'Bulbasaur',   species: 'Bulbasaur',   primaryType: 'Grass' },
  ivysaur:     { name: 'Ivysaur',     species: 'Ivysaur',     primaryType: 'Grass' },
  venusaur:    { name: 'Venusaur',    species: 'Venusaur',    primaryType: 'Grass' },
  charmander:  { name: 'Charmander',  species: 'Charmander',  primaryType: 'Fire' },
  charmeleon:  { name: 'Charmeleon',  species: 'Charmeleon',  primaryType: 'Fire' },
  charizard:   { name: 'Charizard',   species: 'Charizard',   primaryType: 'Fire' },
  squirtle:    { name: 'Squirtle',    species: 'Squirtle',    primaryType: 'Water' },
  wartortle:   { name: 'Wartortle',   species: 'Wartortle',   primaryType: 'Water' },
  blastoise:   { name: 'Blastoise',   species: 'Blastoise',   primaryType: 'Water' },
  caterpie:    { name: 'Caterpie',    species: 'Caterpie',    primaryType: 'Bug' },
  metapod:     { name: 'Metapod',     species: 'Metapod',     primaryType: 'Bug' },
  butterfree:  { name: 'Butterfree',  species: 'Butterfree',  primaryType: 'Bug' },
  weedle:      { name: 'Weedle',      species: 'Weedle',      primaryType: 'Bug' },
  kakuna:      { name: 'Kakuna',      species: 'Kakuna',      primaryType: 'Bug' },
  beedrill:    { name: 'Beedrill',    species: 'Beedrill',    primaryType: 'Bug' },
  pidgey:      { name: 'Pidgey',      species: 'Pidgey',      primaryType: 'Normal' },
  pidgeotto:   { name: 'Pidgeotto',   species: 'Pidgeotto',   primaryType: 'Normal' },
  pidgeot:     { name: 'Pidgeot',     species: 'Pidgeot',     primaryType: 'Normal' },
  rattata:     { name: 'Rattata',     species: 'Rattata',     primaryType: 'Normal' },
  raticate:    { name: 'Raticate',    species: 'Raticate',    primaryType: 'Normal' },
  spearow:     { name: 'Spearow',     species: 'Spearow',     primaryType: 'Normal' },
  fearow:      { name: 'Fearow',      species: 'Fearow',      primaryType: 'Normal' },
  ekans:       { name: 'Ekans',       species: 'Ekans',       primaryType: 'Poison' },
  arbok:       { name: 'Arbok',       species: 'Arbok',       primaryType: 'Poison' },
  pikachu:     { name: 'Pikachu',     species: 'Pikachu',     primaryType: 'Electric' },
  raichu:      { name: 'Raichu',      species: 'Raichu',      primaryType: 'Electric' },
  sandshrew:   { name: 'Sandshrew',   species: 'Sandshrew',   primaryType: 'Ground' },
  sandslash:   { name: 'Sandslash',   species: 'Sandslash',   primaryType: 'Ground' },
  clefairy:    { name: 'Clefairy',    species: 'Clefairy',    primaryType: 'Normal' },
  clefable:    { name: 'Clefable',    species: 'Clefable',    primaryType: 'Normal' },
  vulpix:      { name: 'Vulpix',      species: 'Vulpix',      primaryType: 'Fire' },
  ninetales:   { name: 'Ninetales',   species: 'Ninetales',   primaryType: 'Fire' },
  jigglypuff:  { name: 'Jigglypuff',  species: 'Jigglypuff',  primaryType: 'Normal' },
  wigglytuff:  { name: 'Wigglytuff',  species: 'Wigglytuff',  primaryType: 'Normal' },
  zubat:       { name: 'Zubat',       species: 'Zubat',       primaryType: 'Poison' },
  golbat:      { name: 'Golbat',      species: 'Golbat',      primaryType: 'Poison' },
  oddish:      { name: 'Oddish',      species: 'Oddish',      primaryType: 'Grass' },
  gloom:       { name: 'Gloom',       species: 'Gloom',       primaryType: 'Grass' },
  vileplume:   { name: 'Vileplume',   species: 'Vileplume',   primaryType: 'Grass' },
  paras:       { name: 'Paras',       species: 'Paras',       primaryType: 'Bug' },
  parasect:    { name: 'Parasect',    species: 'Parasect',    primaryType: 'Bug' },
  venonat:     { name: 'Venonat',     species: 'Venonat',     primaryType: 'Bug' },
  venomoth:    { name: 'Venomoth',    species: 'Venomoth',    primaryType: 'Bug' },
  diglett:     { name: 'Diglett',     species: 'Diglett',     primaryType: 'Ground' },
  dugtrio:     { name: 'Dugtrio',     species: 'Dugtrio',     primaryType: 'Ground' },
  meowth:      { name: 'Meowth',      species: 'Meowth',      primaryType: 'Normal' },
  persian:     { name: 'Persian',     species: 'Persian',     primaryType: 'Normal' },
  psyduck:     { name: 'Psyduck',     species: 'Psyduck',     primaryType: 'Water' },
  golduck:     { name: 'Golduck',     species: 'Golduck',     primaryType: 'Water' },
  mankey:      { name: 'Mankey',      species: 'Mankey',      primaryType: 'Fighting' },
  primeape:    { name: 'Primeape',    species: 'Primeape',    primaryType: 'Fighting' },
  growlithe:   { name: 'Growlithe',   species: 'Growlithe',   primaryType: 'Fire' },
  arcanine:    { name: 'Arcanine',    species: 'Arcanine',    primaryType: 'Fire' },
  poliwag:     { name: 'Poliwag',     species: 'Poliwag',     primaryType: 'Water' },
  poliwhirl:   { name: 'Poliwhirl',   species: 'Poliwhirl',   primaryType: 'Water' },
  poliwrath:   { name: 'Poliwrath',   species: 'Poliwrath',   primaryType: 'Water' },
  abra:        { name: 'Abra',        species: 'Abra',        primaryType: 'Psychic' },
  kadabra:     { name: 'Kadabra',     species: 'Kadabra',     primaryType: 'Psychic' },
  alakazam:    { name: 'Alakazam',    species: 'Alakazam',    primaryType: 'Psychic' },
  machop:      { name: 'Machop',      species: 'Machop',      primaryType: 'Fighting' },
  machoke:     { name: 'Machoke',     species: 'Machoke',     primaryType: 'Fighting' },
  machamp:     { name: 'Machamp',     species: 'Machamp',     primaryType: 'Fighting' },
  bellsprout:  { name: 'Bellsprout',  species: 'Bellsprout',  primaryType: 'Grass' },
  weepinbell:  { name: 'Weepinbell',  species: 'Weepinbell',  primaryType: 'Grass' },
  victreebel:  { name: 'Victreebel',  species: 'Victreebel',  primaryType: 'Grass' },
  tentacool:   { name: 'Tentacool',   species: 'Tentacool',   primaryType: 'Water' },
  tentacruel:  { name: 'Tentacruel',  species: 'Tentacruel',  primaryType: 'Water' },
  geodude:     { name: 'Geodude',     species: 'Geodude',     primaryType: 'Rock' },
  graveler:    { name: 'Graveler',    species: 'Graveler',    primaryType: 'Rock' },
  golem:       { name: 'Golem',       species: 'Golem',       primaryType: 'Rock' },
  ponyta:      { name: 'Ponyta',      species: 'Ponyta',      primaryType: 'Fire' },
  rapidash:    { name: 'Rapidash',    species: 'Rapidash',    primaryType: 'Fire' },
  slowpoke:    { name: 'Slowpoke',    species: 'Slowpoke',    primaryType: 'Water' },
  slowbro:     { name: 'Slowbro',     species: 'Slowbro',     primaryType: 'Water' },
  magnemite:   { name: 'Magnemite',   species: 'Magnemite',   primaryType: 'Electric' },
  magneton:    { name: 'Magneton',    species: 'Magneton',    primaryType: 'Electric' },
  farfetchd:   { name: "Farfetch'd",  species: "Farfetch'd",  primaryType: 'Normal' },
  doduo:       { name: 'Doduo',       species: 'Doduo',       primaryType: 'Normal' },
  dodrio:      { name: 'Dodrio',      species: 'Dodrio',      primaryType: 'Normal' },
  seel:        { name: 'Seel',        species: 'Seel',        primaryType: 'Water' },
  dewgong:     { name: 'Dewgong',     species: 'Dewgong',     primaryType: 'Water' },
  grimer:      { name: 'Grimer',      species: 'Grimer',      primaryType: 'Poison' },
  muk:         { name: 'Muk',         species: 'Muk',         primaryType: 'Poison' },
  shellder:    { name: 'Shellder',    species: 'Shellder',    primaryType: 'Water' },
  cloyster:    { name: 'Cloyster',    species: 'Cloyster',    primaryType: 'Water' },
  gastly:      { name: 'Gastly',      species: 'Gastly',      primaryType: 'Ghost' },
  haunter:     { name: 'Haunter',     species: 'Haunter',     primaryType: 'Ghost' },
  gengar:      { name: 'Gengar',      species: 'Gengar',      primaryType: 'Ghost' },
  onix:        { name: 'Onix',        species: 'Onix',        primaryType: 'Rock' },
  drowzee:     { name: 'Drowzee',     species: 'Drowzee',     primaryType: 'Psychic' },
  hypno:       { name: 'Hypno',       species: 'Hypno',       primaryType: 'Psychic' },
  krabby:      { name: 'Krabby',      species: 'Krabby',      primaryType: 'Water' },
  kingler:     { name: 'Kingler',     species: 'Kingler',     primaryType: 'Water' },
  voltorb:     { name: 'Voltorb',     species: 'Voltorb',     primaryType: 'Electric' },
  electrode:   { name: 'Electrode',   species: 'Electrode',   primaryType: 'Electric' },
  exeggcute:   { name: 'Exeggcute',   species: 'Exeggcute',   primaryType: 'Grass' },
  exeggutor:   { name: 'Exeggutor',   species: 'Exeggutor',   primaryType: 'Grass' },
  cubone:      { name: 'Cubone',      species: 'Cubone',      primaryType: 'Ground' },
  marowak:     { name: 'Marowak',     species: 'Marowak',     primaryType: 'Ground' },
  hitmonlee:   { name: 'Hitmonlee',   species: 'Hitmonlee',   primaryType: 'Fighting' },
  hitmonchan:  { name: 'Hitmonchan',  species: 'Hitmonchan',  primaryType: 'Fighting' },
  lickitung:   { name: 'Lickitung',   species: 'Lickitung',   primaryType: 'Normal' },
  koffing:     { name: 'Koffing',     species: 'Koffing',     primaryType: 'Poison' },
  weezing:     { name: 'Weezing',     species: 'Weezing',     primaryType: 'Poison' },
  rhyhorn:     { name: 'Rhyhorn',     species: 'Rhyhorn',     primaryType: 'Ground' },
  rhydon:      { name: 'Rhydon',      species: 'Rhydon',      primaryType: 'Ground' },
  chansey:     { name: 'Chansey',     species: 'Chansey',     primaryType: 'Normal' },
  kangaskhan:  { name: 'Kangaskhan',  species: 'Kangaskhan',  primaryType: 'Normal' },
  horsea:      { name: 'Horsea',      species: 'Horsea',      primaryType: 'Water' },
  seadra:      { name: 'Seadra',      species: 'Seadra',      primaryType: 'Water' },
  goldeen:     { name: 'Goldeen',     species: 'Goldeen',     primaryType: 'Water' },
  seaking:     { name: 'Seaking',     species: 'Seaking',     primaryType: 'Water' },
  staryu:      { name: 'Staryu',      species: 'Staryu',      primaryType: 'Water' },
  starmie:     { name: 'Starmie',     species: 'Starmie',     primaryType: 'Water' },
  mrmime:      { name: 'Mr. Mime',    species: 'Mr. Mime',    primaryType: 'Psychic' },
  scyther:     { name: 'Scyther',     species: 'Scyther',     primaryType: 'Bug' },
  jynx:        { name: 'Jynx',        species: 'Jynx',        primaryType: 'Ice' },
  electabuzz:  { name: 'Electabuzz',  species: 'Electabuzz',  primaryType: 'Electric' },
  magmar:      { name: 'Magmar',      species: 'Magmar',      primaryType: 'Fire' },
  pinsir:      { name: 'Pinsir',      species: 'Pinsir',      primaryType: 'Bug' },
  tauros:      { name: 'Tauros',      species: 'Tauros',      primaryType: 'Normal' },
  magikarp:    { name: 'Magikarp',    species: 'Magikarp',    primaryType: 'Water' },
  gyarados:    { name: 'Gyarados',    species: 'Gyarados',    primaryType: 'Water' },
  lapras:      { name: 'Lapras',      species: 'Lapras',      primaryType: 'Water' },
  ditto:       { name: 'Ditto',       species: 'Ditto',       primaryType: 'Normal' },
  eevee:       { name: 'Eevee',       species: 'Eevee',       primaryType: 'Normal' },
  vaporeon:    { name: 'Vaporeon',    species: 'Vaporeon',    primaryType: 'Water' },
  jolteon:     { name: 'Jolteon',     species: 'Jolteon',     primaryType: 'Electric' },
  flareon:     { name: 'Flareon',     species: 'Flareon',     primaryType: 'Fire' },
  porygon:     { name: 'Porygon',     species: 'Porygon',     primaryType: 'Normal' },
  omanyte:     { name: 'Omanyte',     species: 'Omanyte',     primaryType: 'Rock' },
  omastar:     { name: 'Omastar',     species: 'Omastar',     primaryType: 'Rock' },
  kabuto:      { name: 'Kabuto',      species: 'Kabuto',      primaryType: 'Rock' },
  kabutops:    { name: 'Kabutops',    species: 'Kabutops',    primaryType: 'Rock' },
  aerodactyl:  { name: 'Aerodactyl',  species: 'Aerodactyl',  primaryType: 'Rock' },
  snorlax:     { name: 'Snorlax',     species: 'Snorlax',     primaryType: 'Normal' },
  dratini:     { name: 'Dratini',     species: 'Dratini',     primaryType: 'Dragon' },
  dragonair:   { name: 'Dragonair',   species: 'Dragonair',   primaryType: 'Dragon' },
  dragonite:   { name: 'Dragonite',   species: 'Dragonite',   primaryType: 'Dragon' },

  // Gen 2
  chikorita:   { name: 'Chikorita',   species: 'Chikorita',   primaryType: 'Grass' },
  bayleef:     { name: 'Bayleef',     species: 'Bayleef',     primaryType: 'Grass' },
  meganium:    { name: 'Meganium',    species: 'Meganium',    primaryType: 'Grass' },
  cyndaquil:   { name: 'Cyndaquil',   species: 'Cyndaquil',   primaryType: 'Fire' },
  quilava:     { name: 'Quilava',     species: 'Quilava',     primaryType: 'Fire' },
  typhlosion:  { name: 'Typhlosion',  species: 'Typhlosion',  primaryType: 'Fire' },
  totodile:    { name: 'Totodile',    species: 'Totodile',    primaryType: 'Water' },
  croconaw:    { name: 'Croconaw',    species: 'Croconaw',    primaryType: 'Water' },
  feraligatr:  { name: 'Feraligatr',  species: 'Feraligatr',  primaryType: 'Water' },
  sentret:     { name: 'Sentret',     species: 'Sentret',     primaryType: 'Normal' },
  furret:      { name: 'Furret',      species: 'Furret',      primaryType: 'Normal' },
  hoothoot:    { name: 'Hoothoot',    species: 'Hoothoot',    primaryType: 'Normal' },
  noctowl:     { name: 'Noctowl',     species: 'Noctowl',     primaryType: 'Normal' },
  ledyba:      { name: 'Ledyba',      species: 'Ledyba',      primaryType: 'Bug' },
  ledian:      { name: 'Ledian',      species: 'Ledian',      primaryType: 'Bug' },
  spinarak:    { name: 'Spinarak',    species: 'Spinarak',    primaryType: 'Bug' },
  ariados:     { name: 'Ariados',     species: 'Ariados',     primaryType: 'Bug' },
  crobat:      { name: 'Crobat',      species: 'Crobat',      primaryType: 'Poison' },
  pichu:       { name: 'Pichu',       species: 'Pichu',       primaryType: 'Electric' },
  cleffa:      { name: 'Cleffa',      species: 'Cleffa',      primaryType: 'Normal' },
  igglybuff:   { name: 'Igglybuff',   species: 'Igglybuff',   primaryType: 'Normal' },
  togepi:      { name: 'Togepi',      species: 'Togepi',      primaryType: 'Normal' },
  togetic:     { name: 'Togetic',     species: 'Togetic',     primaryType: 'Normal' },
  natu:        { name: 'Natu',        species: 'Natu',        primaryType: 'Psychic' },
  xatu:        { name: 'Xatu',        species: 'Xatu',        primaryType: 'Psychic' },
  mareep:      { name: 'Mareep',      species: 'Mareep',      primaryType: 'Electric' },
  flaaffy:     { name: 'Flaaffy',     species: 'Flaaffy',     primaryType: 'Electric' },
  ampharos:    { name: 'Ampharos',    species: 'Ampharos',    primaryType: 'Electric' },
  bellossom:   { name: 'Bellossom',   species: 'Bellossom',   primaryType: 'Grass' },
  marill:      { name: 'Marill',      species: 'Marill',      primaryType: 'Water' },
  azumarill:   { name: 'Azumarill',   species: 'Azumarill',   primaryType: 'Water' },
  sudowoodo:   { name: 'Sudowoodo',   species: 'Sudowoodo',   primaryType: 'Rock' },
  politoed:    { name: 'Politoed',    species: 'Politoed',    primaryType: 'Water' },
  hoppip:      { name: 'Hoppip',      species: 'Hoppip',      primaryType: 'Grass' },
  skiploom:    { name: 'Skiploom',    species: 'Skiploom',    primaryType: 'Grass' },
  jumpluff:    { name: 'Jumpluff',    species: 'Jumpluff',    primaryType: 'Grass' },
  aipom:       { name: 'Aipom',       species: 'Aipom',       primaryType: 'Normal' },
  sunkern:     { name: 'Sunkern',     species: 'Sunkern',     primaryType: 'Grass' },
  sunflora:    { name: 'Sunflora',    species: 'Sunflora',    primaryType: 'Grass' },
  yanma:       { name: 'Yanma',       species: 'Yanma',       primaryType: 'Bug' },
  wooper:      { name: 'Wooper',      species: 'Wooper',      primaryType: 'Water' },
  quagsire:    { name: 'Quagsire',    species: 'Quagsire',    primaryType: 'Water' },
  espeon:      { name: 'Espeon',      species: 'Espeon',      primaryType: 'Psychic' },
  umbreon:     { name: 'Umbreon',     species: 'Umbreon',     primaryType: 'Dark' },
  murkrow:     { name: 'Murkrow',     species: 'Murkrow',     primaryType: 'Dark' },
  slowking:    { name: 'Slowking',    species: 'Slowking',    primaryType: 'Water' },
  misdreavus:  { name: 'Misdreavus',  species: 'Misdreavus',  primaryType: 'Ghost' },
  unown:       { name: 'Unown',       species: 'Unown',       primaryType: 'Psychic' },
  wobbuffet:   { name: 'Wobbuffet',   species: 'Wobbuffet',   primaryType: 'Psychic' },
  girafarig:   { name: 'Girafarig',   species: 'Girafarig',   primaryType: 'Normal' },
  pineco:      { name: 'Pineco',      species: 'Pineco',      primaryType: 'Bug' },
  forretress:  { name: 'Forretress',  species: 'Forretress',  primaryType: 'Bug' },
  dunsparce:   { name: 'Dunsparce',   species: 'Dunsparce',   primaryType: 'Normal' },
  gligar:      { name: 'Gligar',      species: 'Gligar',      primaryType: 'Ground' },
  steelix:     { name: 'Steelix',     species: 'Steelix',     primaryType: 'Steel' },
  snubbull:    { name: 'Snubbull',    species: 'Snubbull',    primaryType: 'Normal' },
  granbull:    { name: 'Granbull',    species: 'Granbull',    primaryType: 'Normal' },
  qwilfish:    { name: 'Qwilfish',    species: 'Qwilfish',    primaryType: 'Water' },
  scizor:      { name: 'Scizor',      species: 'Scizor',      primaryType: 'Bug' },
  shuckle:     { name: 'Shuckle',     species: 'Shuckle',     primaryType: 'Bug' },
  heracross:   { name: 'Heracross',   species: 'Heracross',   primaryType: 'Bug' },
  sneasel:     { name: 'Sneasel',     species: 'Sneasel',     primaryType: 'Dark' },
  teddiursa:   { name: 'Teddiursa',   species: 'Teddiursa',   primaryType: 'Normal' },
  ursaring:    { name: 'Ursaring',    species: 'Ursaring',    primaryType: 'Normal' },
  slugma:      { name: 'Slugma',      species: 'Slugma',      primaryType: 'Fire' },
  magcargo:    { name: 'Magcargo',    species: 'Magcargo',    primaryType: 'Fire' },
  swinub:      { name: 'Swinub',      species: 'Swinub',      primaryType: 'Ice' },
  piloswine:   { name: 'Piloswine',   species: 'Piloswine',   primaryType: 'Ice' },
  corsola:     { name: 'Corsola',     species: 'Corsola',     primaryType: 'Water' },
  remoraid:    { name: 'Remoraid',    species: 'Remoraid',    primaryType: 'Water' },
  octillery:   { name: 'Octillery',   species: 'Octillery',   primaryType: 'Water' },
  delibird:    { name: 'Delibird',    species: 'Delibird',    primaryType: 'Ice' },
  mantine:     { name: 'Mantine',     species: 'Mantine',     primaryType: 'Water' },
  skarmory:    { name: 'Skarmory',    species: 'Skarmory',    primaryType: 'Steel' },
  houndour:    { name: 'Houndour',    species: 'Houndour',    primaryType: 'Dark' },
  houndoom:    { name: 'Houndoom',    species: 'Houndoom',    primaryType: 'Dark' },
  kingdra:     { name: 'Kingdra',     species: 'Kingdra',     primaryType: 'Water' },
  phanpy:      { name: 'Phanpy',      species: 'Phanpy',      primaryType: 'Ground' },
  donphan:     { name: 'Donphan',     species: 'Donphan',     primaryType: 'Ground' },
  porygon2:    { name: 'Porygon2',    species: 'Porygon2',    primaryType: 'Normal' },
  stantler:    { name: 'Stantler',    species: 'Stantler',    primaryType: 'Normal' },
  smeargle:    { name: 'Smeargle',    species: 'Smeargle',    primaryType: 'Normal' },
  tyrogue:     { name: 'Tyrogue',     species: 'Tyrogue',     primaryType: 'Fighting' },
  hitmontop:   { name: 'Hitmontop',   species: 'Hitmontop',   primaryType: 'Fighting' },
  smoochum:    { name: 'Smoochum',    species: 'Smoochum',    primaryType: 'Ice' },
  elekid:      { name: 'Elekid',      species: 'Elekid',      primaryType: 'Electric' },
  magby:       { name: 'Magby',       species: 'Magby',       primaryType: 'Fire' },
  miltank:     { name: 'Miltank',     species: 'Miltank',     primaryType: 'Normal' },
  blissey:     { name: 'Blissey',     species: 'Blissey',     primaryType: 'Normal' },
  larvitar:    { name: 'Larvitar',    species: 'Larvitar',    primaryType: 'Rock' },
  pupitar:     { name: 'Pupitar',     species: 'Pupitar',     primaryType: 'Rock' },
  tyranitar:   { name: 'Tyranitar',   species: 'Tyranitar',   primaryType: 'Rock' },

  // Gen 4 starters & Platinum natives
  turtwig:     { name: 'Turtwig',     species: 'Turtwig',     primaryType: 'Grass' },
  grotle:      { name: 'Grotle',      species: 'Grotle',      primaryType: 'Grass' },
  torterra:    { name: 'Torterra',    species: 'Torterra',    primaryType: 'Grass' },
  chimchar:    { name: 'Chimchar',    species: 'Chimchar',    primaryType: 'Fire' },
  monferno:    { name: 'Monferno',    species: 'Monferno',    primaryType: 'Fire' },
  infernape:   { name: 'Infernape',   species: 'Infernape',   primaryType: 'Fire' },
  piplup:      { name: 'Piplup',      species: 'Piplup',      primaryType: 'Water' },
  prinplup:    { name: 'Prinplup',    species: 'Prinplup',    primaryType: 'Water' },
  empoleon:    { name: 'Empoleon',    species: 'Empoleon',    primaryType: 'Water' },
  starly:      { name: 'Starly',      species: 'Starly',      primaryType: 'Normal' },
  staravia:    { name: 'Staravia',    species: 'Staravia',    primaryType: 'Normal' },
  staraptor:   { name: 'Staraptor',   species: 'Staraptor',   primaryType: 'Normal' },
  bidoof:      { name: 'Bidoof',      species: 'Bidoof',      primaryType: 'Normal' },
  bibarel:     { name: 'Bibarel',     species: 'Bibarel',     primaryType: 'Normal' },
  kricketot:   { name: 'Kricketot',   species: 'Kricketot',   primaryType: 'Bug' },
  kricketune:  { name: 'Kricketune',  species: 'Kricketune',  primaryType: 'Bug' },
  shinx:       { name: 'Shinx',       species: 'Shinx',       primaryType: 'Electric' },
  luxio:       { name: 'Luxio',       species: 'Luxio',       primaryType: 'Electric' },
  luxray:      { name: 'Luxray',      species: 'Luxray',      primaryType: 'Electric' },
  budew:       { name: 'Budew',       species: 'Budew',       primaryType: 'Grass' },
  roserade:    { name: 'Roserade',    species: 'Roserade',    primaryType: 'Grass' },
  cranidos:    { name: 'Cranidos',    species: 'Cranidos',    primaryType: 'Rock' },
  rampardos:   { name: 'Rampardos',   species: 'Rampardos',   primaryType: 'Rock' },
  shieldon:    { name: 'Shieldon',    species: 'Shieldon',    primaryType: 'Rock' },
  bastiodon:   { name: 'Bastiodon',   species: 'Bastiodon',   primaryType: 'Rock' },
  burmy:       { name: 'Burmy',       species: 'Burmy',       primaryType: 'Bug' },
  wormadam:    { name: 'Wormadam',    species: 'Wormadam',    primaryType: 'Bug' },
  mothim:      { name: 'Mothim',      species: 'Mothim',      primaryType: 'Bug' },
  combee:      { name: 'Combee',      species: 'Combee',      primaryType: 'Bug' },
  vespiquen:   { name: 'Vespiquen',   species: 'Vespiquen',   primaryType: 'Bug' },
  pachirisu:   { name: 'Pachirisu',   species: 'Pachirisu',   primaryType: 'Electric' },
  buizel:      { name: 'Buizel',      species: 'Buizel',      primaryType: 'Water' },
  floatzel:    { name: 'Floatzel',    species: 'Floatzel',    primaryType: 'Water' },
  cherubi:     { name: 'Cherubi',     species: 'Cherubi',     primaryType: 'Grass' },
  cherrim:     { name: 'Cherrim',     species: 'Cherrim',     primaryType: 'Grass' },
  shellos:     { name: 'Shellos',     species: 'Shellos',     primaryType: 'Water' },
  gastrodon:   { name: 'Gastrodon',   species: 'Gastrodon',   primaryType: 'Water' },
  ambipom:     { name: 'Ambipom',     species: 'Ambipom',     primaryType: 'Normal' },
  drifloon:    { name: 'Drifloon',    species: 'Drifloon',    primaryType: 'Ghost' },
  drifblim:    { name: 'Drifblim',    species: 'Drifblim',    primaryType: 'Ghost' },
  buneary:     { name: 'Buneary',     species: 'Buneary',     primaryType: 'Normal' },
  lopunny:     { name: 'Lopunny',     species: 'Lopunny',     primaryType: 'Normal' },
  mismagius:   { name: 'Mismagius',   species: 'Mismagius',   primaryType: 'Ghost' },
  honchkrow:   { name: 'Honchkrow',   species: 'Honchkrow',   primaryType: 'Dark' },
  glameow:     { name: 'Glameow',     species: 'Glameow',     primaryType: 'Normal' },
  purugly:     { name: 'Purugly',     species: 'Purugly',     primaryType: 'Normal' },
  chingling:   { name: 'Chingling',   species: 'Chingling',   primaryType: 'Psychic' },
  stunky:      { name: 'Stunky',      species: 'Stunky',      primaryType: 'Poison' },
  skuntank:    { name: 'Skuntank',    species: 'Skuntank',    primaryType: 'Poison' },
  bronzor:     { name: 'Bronzor',     species: 'Bronzor',     primaryType: 'Steel' },
  bronzong:    { name: 'Bronzong',    species: 'Bronzong',    primaryType: 'Steel' },
  bonsly:      { name: 'Bonsly',      species: 'Bonsly',      primaryType: 'Rock' },
  mimejr:      { name: 'Mime Jr.',    species: 'Mime Jr.',    primaryType: 'Psychic' },
  happiny:     { name: 'Happiny',     species: 'Happiny',     primaryType: 'Normal' },
  chatot:      { name: 'Chatot',      species: 'Chatot',      primaryType: 'Normal' },
  spiritomb:   { name: 'Spiritomb',   species: 'Spiritomb',   primaryType: 'Ghost' },
  gible:       { name: 'Gible',       species: 'Gible',       primaryType: 'Dragon' },
  gabite:      { name: 'Gabite',      species: 'Gabite',      primaryType: 'Dragon' },
  garchomp:    { name: 'Garchomp',    species: 'Garchomp',    primaryType: 'Dragon' },
  munchlax:    { name: 'Munchlax',    species: 'Munchlax',    primaryType: 'Normal' },
  riolu:       { name: 'Riolu',       species: 'Riolu',       primaryType: 'Fighting' },
  lucario:     { name: 'Lucario',     species: 'Lucario',     primaryType: 'Fighting' },
  hippopotas:  { name: 'Hippopotas',  species: 'Hippopotas',  primaryType: 'Ground' },
  hippowdon:   { name: 'Hippowdon',   species: 'Hippowdon',   primaryType: 'Ground' },
  skorupi:     { name: 'Skorupi',     species: 'Skorupi',     primaryType: 'Poison' },
  drapion:     { name: 'Drapion',     species: 'Drapion',     primaryType: 'Poison' },
  croagunk:    { name: 'Croagunk',    species: 'Croagunk',    primaryType: 'Poison' },
  toxicroak:   { name: 'Toxicroak',   species: 'Toxicroak',   primaryType: 'Poison' },
  carnivine:   { name: 'Carnivine',   species: 'Carnivine',   primaryType: 'Grass' },
  finneon:     { name: 'Finneon',     species: 'Finneon',     primaryType: 'Water' },
  lumineon:    { name: 'Lumineon',    species: 'Lumineon',    primaryType: 'Water' },
  mantyke:     { name: 'Mantyke',     species: 'Mantyke',     primaryType: 'Water' },
  snover:      { name: 'Snover',      species: 'Snover',      primaryType: 'Grass' },
  abomasnow:   { name: 'Abomasnow',   species: 'Abomasnow',   primaryType: 'Grass' },
  weavile:     { name: 'Weavile',     species: 'Weavile',     primaryType: 'Dark' },
  magnezone:   { name: 'Magnezone',   species: 'Magnezone',   primaryType: 'Electric' },
  lickilicky:  { name: 'Lickilicky',  species: 'Lickilicky',  primaryType: 'Normal' },
  rhyperior:   { name: 'Rhyperior',   species: 'Rhyperior',   primaryType: 'Ground' },
  tangrowth:   { name: 'Tangrowth',   species: 'Tangrowth',   primaryType: 'Grass' },
  electivire:  { name: 'Electivire',  species: 'Electivire',  primaryType: 'Electric' },
  magmortar:   { name: 'Magmortar',   species: 'Magmortar',   primaryType: 'Fire' },
  togekiss:    { name: 'Togekiss',    species: 'Togekiss',    primaryType: 'Normal' },
  yanmega:     { name: 'Yanmega',     species: 'Yanmega',     primaryType: 'Bug' },
  leafeon:     { name: 'Leafeon',     species: 'Leafeon',     primaryType: 'Grass' },
  glaceon:     { name: 'Glaceon',     species: 'Glaceon',     primaryType: 'Ice' },
  gliscor:     { name: 'Gliscor',     species: 'Gliscor',     primaryType: 'Ground' },
  mamoswine:   { name: 'Mamoswine',   species: 'Mamoswine',   primaryType: 'Ice' },
  porygonz:    { name: 'Porygon-Z',   species: 'Porygon-Z',   primaryType: 'Normal' },
  gallade:     { name: 'Gallade',     species: 'Gallade',     primaryType: 'Psychic' },
  probopass:   { name: 'Probopass',   species: 'Probopass',   primaryType: 'Rock' },
  dusknoir:    { name: 'Dusknoir',    species: 'Dusknoir',    primaryType: 'Ghost' },
  froslass:    { name: 'Froslass',    species: 'Froslass',    primaryType: 'Ice' },
  rotom:       { name: 'Rotom',       species: 'Rotom',       primaryType: 'Electric' },
};

export function searchPokedex(query: string): PokedexEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return Object.values(POKEDEX_DATA)
    .filter(
      (entry) =>
        entry.name.toLowerCase().includes(q) ||
        entry.species.toLowerCase().includes(q)
    )
    .slice(0, 10);
}

export function getPokedexEntry(name: string): PokedexEntry | undefined {
  return POKEDEX_DATA[name.toLowerCase()];
}

export function getPrimaryType(species: string): string | undefined {
  return getPokedexEntry(species)?.primaryType;
}
