// Simplified Pokedex with Gen 4 (Diamond/Pearl/Platinum) focus
// This includes primary types for soul-locke rules

export interface PokedexEntry {
  name: string;
  species: string;
  primaryType: string;
}

// Comprehensive Gen 4 Pokedex entries
const POKEDEX_DATA: Record<string, PokedexEntry> = {
  'bulbasaur': { name: 'Bulbasaur', species: 'Bulbasaur', primaryType: 'Grass' },
  'ivysaur': { name: 'Ivysaur', species: 'Ivysaur', primaryType: 'Grass' },
  'venusaur': { name: 'Venusaur', species: 'Venusaur', primaryType: 'Grass' },
  'charmander': { name: 'Charmander', species: 'Charmander', primaryType: 'Fire' },
  'charmeleon': { name: 'Charmeleon', species: 'Charmeleon', primaryType: 'Fire' },
  'charizard': { name: 'Charizard', species: 'Charizard', primaryType: 'Fire' },
  'squirtle': { name: 'Squirtle', species: 'Squirtle', primaryType: 'Water' },
  'wartortle': { name: 'Wartortle', species: 'Wartortle', primaryType: 'Water' },
  'blastoise': { name: 'Blastoise', species: 'Blastoise', primaryType: 'Water' },
  'pidgeot': { name: 'Pidgeot', species: 'Pidgeot', primaryType: 'Normal' },
  'pidgeotto': { name: 'Pidgeotto', species: 'Pidgeotto', primaryType: 'Normal' },
  'pidgeot': { name: 'Pidgeot', species: 'Pidgeot', primaryType: 'Normal' },
  'rattata': { name: 'Rattata', species: 'Rattata', primaryType: 'Normal' },
  'raticate': { name: 'Raticate', species: 'Raticate', primaryType: 'Normal' },
  'spearow': { name: 'Spearow', species: 'Spearow', primaryType: 'Normal' },
  'fearow': { name: 'Fearow', species: 'Fearow', primaryType: 'Normal' },
  'ekans': { name: 'Ekans', species: 'Ekans', primaryType: 'Poison' },
  'arbok': { name: 'Arbok', species: 'Arbok', primaryType: 'Poison' },
  'pikachu': { name: 'Pikachu', species: 'Pikachu', primaryType: 'Electric' },
  'raichu': { name: 'Raichu', species: 'Raichu', primaryType: 'Electric' },
  'clefairy': { name: 'Clefairy', species: 'Clefairy', primaryType: 'Normal' },
  'clefable': { name: 'Clefable', species: 'Clefable', primaryType: 'Normal' },
  'vulpix': { name: 'Vulpix', species: 'Vulpix', primaryType: 'Fire' },
  'ninetales': { name: 'Ninetales', species: 'Ninetales', primaryType: 'Fire' },
  'jigglypuff': { name: 'Jigglypuff', species: 'Jigglypuff', primaryType: 'Normal' },
  'wigglytuff': { name: 'Wigglytuff', species: 'Wigglytuff', primaryType: 'Normal' },
  'zubat': { name: 'Zubat', species: 'Zubat', primaryType: 'Poison' },
  'golbat': { name: 'Golbat', species: 'Golbat', primaryType: 'Poison' },
  'oddish': { name: 'Oddish', species: 'Oddish', primaryType: 'Grass' },
  'gloom': { name: 'Gloom', species: 'Gloom', primaryType: 'Grass' },
  'vileplume': { name: 'Vileplume', species: 'Vileplume', primaryType: 'Grass' },
  'paras': { name: 'Paras', species: 'Paras', primaryType: 'Bug' },
  'parasect': { name: 'Parasect', species: 'Parasect', primaryType: 'Bug' },
  'venonat': { name: 'Venonat', species: 'Venonat', primaryType: 'Bug' },
  'venomoth': { name: 'Venomoth', species: 'Venomoth', primaryType: 'Bug' },
  'diglett': { name: 'Diglett', species: 'Diglett', primaryType: 'Ground' },
  'dugtrio': { name: 'Dugtrio', species: 'Dugtrio', primaryType: 'Ground' },
  'meowth': { name: 'Meowth', species: 'Meowth', primaryType: 'Normal' },
  'persian': { name: 'Persian', species: 'Persian', primaryType: 'Normal' },
  'psyduck': { name: 'Psyduck', species: 'Psyduck', primaryType: 'Water' },
  'golduck': { name: 'Golduck', species: 'Golduck', primaryType: 'Water' },
  'mankey': { name: 'Mankey', species: 'Mankey', primaryType: 'Fighting' },
  'primeape': { name: 'Primeape', species: 'Primeape', primaryType: 'Fighting' },
  'growlithe': { name: 'Growlithe', species: 'Growlithe', primaryType: 'Fire' },
  'arcanine': { name: 'Arcanine', species: 'Arcanine', primaryType: 'Fire' },
  'poliwag': { name: 'Poliwag', species: 'Poliwag', primaryType: 'Water' },
  'poliwhirl': { name: 'Poliwhirl', species: 'Poliwhirl', primaryType: 'Water' },
  'poliwrath': { name: 'Poliwrath', species: 'Poliwrath', primaryType: 'Water' },
  'abra': { name: 'Abra', species: 'Abra', primaryType: 'Psychic' },
  'kadabra': { name: 'Kadabra', species: 'Kadabra', primaryType: 'Psychic' },
  'alakazam': { name: 'Alakazam', species: 'Alakazam', primaryType: 'Psychic' },
  'machop': { name: 'Machop', species: 'Machop', primaryType: 'Fighting' },
  'machoke': { name: 'Machoke', species: 'Machoke', primaryType: 'Fighting' },
  'machamp': { name: 'Machamp', species: 'Machamp', primaryType: 'Fighting' },
  'bellsprout': { name: 'Bellsprout', species: 'Bellsprout', primaryType: 'Grass' },
  'weepinbell': { name: 'Weepinbell', species: 'Weepinbell', primaryType: 'Grass' },
  'victreebel': { name: 'Victreebel', species: 'Victreebel', primaryType: 'Grass' },
  'tentacool': { name: 'Tentacool', species: 'Tentacool', primaryType: 'Water' },
  'tentacruel': { name: 'Tentacruel', species: 'Tentacruel', primaryType: 'Water' },
  'geodude': { name: 'Geodude', species: 'Geodude', primaryType: 'Rock' },
  'graveler': { name: 'Graveler', species: 'Graveler', primaryType: 'Rock' },
  'golem': { name: 'Golem', species: 'Golem', primaryType: 'Rock' },
  'ponyta': { name: 'Ponyta', species: 'Ponyta', primaryType: 'Fire' },
  'rapidash': { name: 'Rapidash', species: 'Rapidash', primaryType: 'Fire' },
  'slowpoke': { name: 'Slowpoke', species: 'Slowpoke', primaryType: 'Water' },
  'slowbro': { name: 'Slowbro', species: 'Slowbro', primaryType: 'Water' },
  'seel': { name: 'Seel', species: 'Seel', primaryType: 'Water' },
  'dewgong': { name: 'Dewgong', species: 'Dewgong', primaryType: 'Water' },
  'shellder': { name: 'Shellder', species: 'Shellder', primaryType: 'Water' },
  'cloyster': { name: 'Cloyster', species: 'Cloyster', primaryType: 'Water' },
  'gastly': { name: 'Gastly', species: 'Gastly', primaryType: 'Ghost' },
  'haunter': { name: 'Haunter', species: 'Haunter', primaryType: 'Ghost' },
  'gengar': { name: 'Gengar', species: 'Gengar', primaryType: 'Ghost' },
  'onix': { name: 'Onix', species: 'Onix', primaryType: 'Rock' },
  'drowzee': { name: 'Drowzee', species: 'Drowzee', primaryType: 'Psychic' },
  'hypno': { name: 'Hypno', species: 'Hypno', primaryType: 'Psychic' },
  'krabby': { name: 'Krabby', species: 'Krabby', primaryType: 'Water' },
  'kingler': { name: 'Kingler', species: 'Kingler', primaryType: 'Water' },
  'voltorb': { name: 'Voltorb', species: 'Voltorb', primaryType: 'Electric' },
  'electrode': { name: 'Electrode', species: 'Electrode', primaryType: 'Electric' },
  'exeggcute': { name: 'Exeggcute', species: 'Exeggcute', primaryType: 'Grass' },
  'exeggutor': { name: 'Exeggutor', species: 'Exeggutor', primaryType: 'Grass' },
  'cubone': { name: 'Cubone', species: 'Cubone', primaryType: 'Ground' },
  'marowak': { name: 'Marowak', species: 'Marowak', primaryType: 'Ground' },
  'hitmonlee': { name: 'Hitmonlee', species: 'Hitmonlee', primaryType: 'Fighting' },
  'hitmonchan': { name: 'Hitmonchan', species: 'Hitmonchan', primaryType: 'Fighting' },
  'lickitung': { name: 'Lickitung', species: 'Lickitung', primaryType: 'Normal' },
  'koffing': { name: 'Koffing', species: 'Koffing', primaryType: 'Poison' },
  'weezing': { name: 'Weezing', species: 'Weezing', primaryType: 'Poison' },
  'rhyhorn': { name: 'Rhyhorn', species: 'Rhyhorn', primaryType: 'Ground' },
  'rhydon': { name: 'Rhydon', species: 'Rhydon', primaryType: 'Ground' },
  'chansey': { name: 'Chansey', species: 'Chansey', primaryType: 'Normal' },
  'kangaskhan': { name: 'Kangaskhan', species: 'Kangaskhan', primaryType: 'Normal' },
  'horsea': { name: 'Horsea', species: 'Horsea', primaryType: 'Water' },
  'seadra': { name: 'Seadra', species: 'Seadra', primaryType: 'Water' },
  'goldeen': { name: 'Goldeen', species: 'Goldeen', primaryType: 'Water' },
  'seaking': { name: 'Seaking', species: 'Seaking', primaryType: 'Water' },
  'staryu': { name: 'Staryu', species: 'Staryu', primaryType: 'Water' },
  'starmie': { name: 'Starmie', species: 'Starmie', primaryType: 'Water' },
  'mr. mime': { name: 'Mr. Mime', species: 'Mr. Mime', primaryType: 'Psychic' },
  'scyther': { name: 'Scyther', species: 'Scyther', primaryType: 'Bug' },
  'jynx': { name: 'Jynx', species: 'Jynx', primaryType: 'Ice' },
  'electabuzz': { name: 'Electabuzz', species: 'Electabuzz', primaryType: 'Electric' },
  'magby': { name: 'Magby', species: 'Magby', primaryType: 'Fire' },
  'magnemite': { name: 'Magnemite', species: 'Magnemite', primaryType: 'Electric' },
  'magneton': { name: 'Magneton', species: 'Magneton', primaryType: 'Electric' },
  'farfetchd': { name: 'Farfetch&apos;d', species: 'Farfetch&apos;d', primaryType: 'Normal' },
  'doduo': { name: 'Doduo', species: 'Doduo', primaryType: 'Normal' },
  'dodrio': { name: 'Dodrio', species: 'Dodrio', primaryType: 'Normal' },
  'seel': { name: 'Seel', species: 'Seel', primaryType: 'Water' },
  'grimer': { name: 'Grimer', species: 'Grimer', primaryType: 'Poison' },
  'muk': { name: 'Muk', species: 'Muk', primaryType: 'Poison' },
  'shellos': { name: 'Shellos', species: 'Shellos', primaryType: 'Water' },
  'gastrodon': { name: 'Gastrodon', species: 'Gastrodon', primaryType: 'Water' },
  'chimchar': { name: 'Chimchar', species: 'Chimchar', primaryType: 'Fire' },
  'monferno': { name: 'Monferno', species: 'Monferno', primaryType: 'Fire' },
  'infernape': { name: 'Infernape', species: 'Infernape', primaryType: 'Fire' },
  'piplup': { name: 'Piplup', species: 'Piplup', primaryType: 'Water' },
  'prinplup': { name: 'Prinplup', species: 'Prinplup', primaryType: 'Water' },
  'empoleon': { name: 'Empoleon', species: 'Empoleon', primaryType: 'Water' },
  'turtwig': { name: 'Turtwig', species: 'Turtwig', primaryType: 'Grass' },
  'grotle': { name: 'Grotle', species: 'Grotle', primaryType: 'Grass' },
  'torterra': { name: 'Torterra', species: 'Torterra', primaryType: 'Grass' },
  'starly': { name: 'Starly', species: 'Starly', primaryType: 'Normal' },
  'staravia': { name: 'Staravia', species: 'Staravia', primaryType: 'Normal' },
  'staraptor': { name: 'Staraptor', species: 'Staraptor', primaryType: 'Normal' },
  'bidoof': { name: 'Bidoof', species: 'Bidoof', primaryType: 'Normal' },
  'bibarel': { name: 'Bibarel', species: 'Bibarel', primaryType: 'Normal' },
  'buneary': { name: 'Buneary', species: 'Buneary', primaryType: 'Normal' },
  'lopunny': { name: 'Lopunny', species: 'Lopunny', primaryType: 'Normal' },
  'gliscor': { name: 'Gliscor', species: 'Gliscor', primaryType: 'Ground' },
  'gible': { name: 'Gible', species: 'Gible', primaryType: 'Dragon' },
  'gabite': { name: 'Gabite', species: 'Gabite', primaryType: 'Dragon' },
  'garchomp': { name: 'Garchomp', species: 'Garchomp', primaryType: 'Dragon' },
  'cyndaquil': { name: 'Cyndaquil', species: 'Cyndaquil', primaryType: 'Fire' },
  'quilava': { name: 'Quilava', species: 'Quilava', primaryType: 'Fire' },
  'typhlosion': { name: 'Typhlosion', species: 'Typhlosion', primaryType: 'Fire' },
  'totodile': { name: 'Totodile', species: 'Totodile', primaryType: 'Water' },
  'croconaw': { name: 'Croconaw', species: 'Croconaw', primaryType: 'Water' },
  'feraligatr': { name: 'Feraligatr', species: 'Feraligatr', primaryType: 'Water' },
  'chikorita': { name: 'Chikorita', species: 'Chikorita', primaryType: 'Grass' },
  'bayleef': { name: 'Bayleef', species: 'Bayleef', primaryType: 'Grass' },
  'meganium': { name: 'Meganium', species: 'Meganium', primaryType: 'Grass' },
  'sentret': { name: 'Sentret', species: 'Sentret', primaryType: 'Normal' },
  'furret': { name: 'Furret', species: 'Furret', primaryType: 'Normal' },
  'hoothoot': { name: 'Hoothoot', species: 'Hoothoot', primaryType: 'Normal' },
  'noctowl': { name: 'Noctowl', species: 'Noctowl', primaryType: 'Normal' },
  'spinarak': { name: 'Spinarak', species: 'Spinarak', primaryType: 'Bug' },
  'girafarig': { name: 'Girafarig', species: 'Girafarig', primaryType: 'Normal' },
  'ledyba': { name: 'Ledyba', species: 'Ledyba', primaryType: 'Bug' },
  'ledian': { name: 'Ledian', species: 'Ledian', primaryType: 'Bug' },
  'delibird': { name: 'Delibird', species: 'Delibird', primaryType: 'Ice' },
  'skarmory': { name: 'Skarmory', species: 'Skarmory', primaryType: 'Steel' },
  'gible': { name: 'Gible', species: 'Gible', primaryType: 'Dragon' },
  'riolu': { name: 'Riolu', species: 'Riolu', primaryType: 'Fighting' },
  'lucario': { name: 'Lucario', species: 'Lucario', primaryType: 'Fighting' },
  'crobat': { name: 'Crobat', species: 'Crobat', primaryType: 'Poison' },
  'pichu': { name: 'Pichu', species: 'Pichu', primaryType: 'Electric' },
  'cloyster': { name: 'Cloyster', species: 'Cloyster', primaryType: 'Water' },
};

export function searchPokedex(query: string): PokedexEntry[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];

  return Object.values(POKEDEX_DATA)
    .filter(
      (entry) =>
        entry.name.toLowerCase().includes(lowerQuery) ||
        entry.species.toLowerCase().includes(lowerQuery)
    )
    .slice(0, 10); // Return top 10 results
}

export function getPokedexEntry(name: string): PokedexEntry | undefined {
  return POKEDEX_DATA[name.toLowerCase()];
}

export function getPrimaryType(species: string): string | undefined {
  const entry = getPokedexEntry(species);
  return entry?.primaryType;
}
